services:
    form_type.product:
        class: AppBundle\Form\ProductType
        calls:
            - [setEntityTranslatorFormEventListener, [@elcodi.entity_translator_form_event_listener]]
        tags:
            - { name: form.type, alias: appbundle_product }